/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\public\assets\models\x-wing.glb 
Author: Blargenswarg (https://sketchfab.com/Blargenswarg)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/x-wing-62762bb28f464d79969b6914c5dd3af3
Title: X-Wing
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/x-wing.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.polySurface149_lambert1_0.geometry} material={materials.lambert1} rotation={[Math.PI / 2, 0, 0]} scale={10} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/x-wing.glb')
